import turtle
arrow=turtle.Turtle()
arrow.begin_fill()
arrow.color("gray","hot pink")
arrow.begin_fill()
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.end_fill()
arrow.penup()
arrow.left(90)
arrow.forward(350)
arrow.left(90)
arrow.forward(50)
arrow.pendown()
arrow.color("lavender","purple")
arrow.begin_fill()
arrow.setheading(90)
arrow.heading()
arrow.circle(60)
arrow.end_fill()
arrow.end_fill()


turtle.done()